# Generated by Django 2.0.4 on 2018-04-16 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='', max_length=64)),
                ('street_number', models.PositiveIntegerField(default=0)),
                ('postal_code', models.CharField(default='', max_length=6)),
                ('city', models.CharField(default='', max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(default='static/tnt/img/no_img.png', upload_to='')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('image', models.ImageField(default='static/tnt/img/no_img.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('name', models.CharField(default='', max_length=64)),
                ('floor', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnt.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tnt.Item')),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tnt.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/tnt/img/no_img.png', upload_to='')),
                ('manufacturer_long', models.CharField(default='', max_length=64)),
                ('manufacturer_short', models.CharField(default='', max_length=64)),
                ('product_model', models.CharField(default='', max_length=64)),
                ('product_family', models.CharField(default='', max_length=64)),
                ('product_info_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnt.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RfDevice',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RfDeviceProduct',
            fields=[
                ('display_text', models.CharField(default='', max_length=64)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RfDeviceType',
            fields=[
                ('display_text', models.CharField(default='', max_length=64)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='rfdevice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnt.RfDeviceType'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tnt.Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='rf_device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tnt.RfDevice'),
        ),
    ]
