# Generated by Django 2.0.4 on 2018-04-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='street_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='building',
            name='street_number',
        ),
    ]
