# Generated by Django 2.0.4 on 2018-04-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0002_auto_20180416_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_info_url',
            new_name='product_info_URL',
        ),
    ]
