# Generated by Django 2.0.4 on 2018-04-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0003_auto_20180416_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfdevice',
            name='device_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfdevice',
            name='low_battery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfdeviceproduct',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rfdevicetype',
            name='type_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rfdevice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rfdeviceproduct',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rfdevicetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
