# Generated by Django 2.0.4 on 2018-05-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0006_auto_20180507_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='building',
        ),
    ]
