# Generated by Django 2.0.4 on 2018-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0007_remove_location_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(default='placeholder', editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='placeholder', editable=False),
        ),
    ]
