# Generated by Django 2.0.4 on 2018-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0008_auto_20180511_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='floor',
            new_name='number',
        ),
        migrations.AddField(
            model_name='floor',
            name='display_text',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
