# Generated by Django 2.0.4 on 2018-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0009_auto_20180516_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image',
            field=models.FileField(default='static/tnt/img/no_img.png', upload_to=''),
        ),
    ]
