# Generated by Django 2.0.4 on 2018-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0011_building_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='image',
        ),
        migrations.AddField(
            model_name='floor',
            name='imageURL',
            field=models.URLField(default='static/tnt/img/no_img.png'),
        ),
    ]
