# Generated by Django 2.0.4 on 2018-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0012_auto_20180516_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='floor',
            name='image_path',
            field=models.FilePathField(default='no_img.png', path='static/tnt/img'),
        ),
    ]
