# Generated by Django 2.0.4 on 2018-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0013_auto_20180517_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image_path',
            field=models.FilePathField(default='no_img.png', path='/static/tnt/img'),
        ),
    ]
