# Generated by Django 2.0.4 on 2018-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0014_auto_20180517_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image_path',
            field=models.FilePathField(default='no_img.png', path='C:\\Users\\Jos van den Eijnden\\OneDrive\\Notebook\\Documenten\\PyCharm\\SCHAT\\deployment\\collected_static\\tnt\\img'),
        ),
    ]
