# Generated by Django 2.0.4 on 2018-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0015_auto_20180517_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image_path',
            field=models.FilePathField(default='no_img.png', max_length=200, path='C:\\Users\\Jos van den Eijnden\\OneDrive\\Notebook\\Documenten\\PyCharm\\SCHAT\\deployment\\collected_static\\tnt\\img'),
        ),
    ]
