# Generated by Django 2.0.4 on 2018-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0016_auto_20180517_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='image_path',
        ),
        migrations.AddField(
            model_name='floor',
            name='image',
            field=models.CharField(default='no_img.png', max_length=200),
        ),
    ]
