# Generated by Django 2.0.4 on 2018-05-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0017_auto_20180517_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Tracker',
        ),
    ]
