# Generated by Django 2.0.4 on 2018-05-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0018_auto_20180517_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='item',
            new_name='tracker',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='rf_device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tnt.RfDevice'),
        ),
    ]
