# Generated by Django 2.0.4 on 2018-05-18 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tnt', '0019_auto_20180518_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('major_version', models.PositiveIntegerField()),
                ('minor_version', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
